export const petSpecies: Readonly<Record<string, readonly string[]>> = {
    Cat: ['Black', 'Gray', 'Orange', 'White', 'Yellow', 'Purple'],
    Dog: ['Blonde', 'Gray', 'Brown', 'Dark Brown', 'Light Brown', 'Purple'],
    Turtle: ['Green', 'Purple'],
    Dino: [],
    Duck: [],
    Raccoon: [],
    Goat: ['Adult', 'Baby'],
    Sheep: ['Adult', 'Baby'],
    Ostrich: ['Adult', 'Baby'],
    Pig: ['Adult', 'Baby'],
    Rabbit: ['Adult', 'Baby'],
    Chicken: ['White Adult', 'White Baby', 'Blue Adult', 'Blue Baby', 'Brown Adult', 'Brown Baby', 'Black Adult', 'Black Baby'],
    Cow: ['White Adult', 'White Baby', 'Brown Adult', 'Brown Baby'],
    Parrot: ['Green Adult', 'Green Baby', 'Blue Adult', 'Blue Baby', 'Golden Joja'],
    Horse: [],
    Junimo: ['White', 'Black', 'Gray', 'Pink', 'Red', 'Orange', 'Yellow', 'Green', 'Cyan', 'Purple', 'Brown'],
};
